"use client";

import { useMemo, useState } from "react";
import type { Company } from "../types";
import { slug,subsectorClass } from "./Essay";

const sectorOrder=["AI Discovery & Bio Foundation Models","Neurotech & BCI","Lab Automation, Agentic Science & Data Infra","Cell/Tissue, Ag-Vet & Biosecurity","Diagnostics, Biosensors & Sample Infra","Genomics, Omics, Proteomics & Imaging","Delivery Systems","Synthesis, Biomanufacturing & Bioprocess"];
function safeLink(value?:string){if(!value)return "";return /^https?:\/\//i.test(value)?value:value.includes(".")?`https://${value}`:""}

function cleanInvestors(value?:string){if(!value)return "Not publicly disclosed";return value.replace(/\s*\[[^\]]*\]/g,"").replace(/\s*\([^)]*\)/g,"").replace(/lead undisclosed/gi,"").split(/[,;]/).map(part=>part.replace(/\s+/g," ").trim()).filter(Boolean).join(", ")||"Not publicly disclosed"}

function Wordmark({company,large=false}:{company:Company;large?:boolean}){return <div className={`company-wordmark ${large?"large":""}`}>{company.logo?<img src={company.logo} alt={`${company.name} logo`}/>:<span>{company.name}</span>}</div>}

function SourceBadge({source}:{source?:string}){const s=(source||"").toLowerCase();if(s.includes("pitch"))return <span className="source-logo" data-tip="pitchbook.com"><img src="/pitchbook-logo.png" alt="PitchBook"/></span>;if(s.includes("harmonic"))return <span className="source-logo" data-tip="harmonic.ai"><img src="/harmonic-logo.png" alt="Harmonic"/></span>;return <span className="source-logo web-source" data-tip="Public web source">◎</span>}

function Detail({company,onClose}:{company:Company;onClose:()=>void}){return <aside className="company-detail" aria-live="polite"><button className="detail-close" onClick={onClose} aria-label="Close company detail">×</button><Wordmark company={company} large/><a className="detail-name" href={safeLink(company.website)||undefined} target="_blank" rel="noreferrer">{company.name} <span>↗</span></a><span className={`detail-subsector ${subsectorClass[company.subsector]||""}`}>{company.subsector}</span><p className="detail-type">— {company.type}</p><dl><dt>HQ</dt><dd>{company.hq||"Not disclosed"}</dd><dt>CEO</dt><dd>{company.ceo||"Not disclosed"}{company.linkedin?<a className="linkedin" href={safeLink(company.linkedin)} target="_blank" rel="noreferrer" aria-label={`${company.ceo} LinkedIn`}>in</a>:null}</dd><dt>Raised</dt><dd>{company.funding||"Not disclosed"} <SourceBadge source={company.fundingSource}/></dd><dt>Investors</dt><dd>{cleanInvestors(company.investors)}</dd></dl><p className="detail-description">{company.description||"Company profile in progress."}</p><div className="detail-news"><span>IN THE NEWS</span>{company.news?<a href={safeLink(company.newsUrl)||undefined} target="_blank" rel="noreferrer">{company.news} ↗</a>:<p>No linked headline available.</p>}</div></aside>}

export function CompanyAtlas({companies,initialCompany}:{companies:Company[];initialCompany?:Company|null}){
  const [query,setQuery]=useState("");const [subsector,setSubsector]=useState("All");const [avOnly,setAvOnly]=useState(false);const [hovered,setHovered]=useState<Company|null>(null);const [pinned,setPinned]=useState<Company|null>(initialCompany||null);
  const normalized=useMemo(()=>companies.map(company=>company.subsector==="Strategic Therapeutics / Asset-Building"?{...company,subsector:"AI Discovery & Bio Foundation Models"}:company),[companies]);
  const visible=useMemo(()=>normalized.filter(c=>(!query||`${c.name} ${c.subsector} ${c.type}`.toLowerCase().includes(query.toLowerCase()))&&(subsector==="All"||c.subsector===subsector)&&(!avOnly||c.av)).sort((a,b)=>a.name.localeCompare(b.name)),[normalized,query,subsector,avOnly]);
  const groups=sectorOrder.map(name=>({name,companies:visible.filter(c=>c.subsector===name)})).filter(group=>group.companies.length);
  const selected=hovered||pinned;
  return <section className="atlas"><div className="atlas-controls"><label className="atlas-search"><span>⌕</span><input placeholder="Search companies..." value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="filter-scroll"><button className={subsector==="All"&&!avOnly?"active":""} onClick={()=>{setSubsector("All");setAvOnly(false)}}>All</button><button className={avOnly?"active av-button":""} onClick={()=>setAvOnly(v=>!v)}>AV Portfolio</button>{sectorOrder.map((item,index)=><button key={item} className={`${subsector===item?"active":""} ${Object.values(subsectorClass)[index]||""}`} onClick={()=>{setSubsector(item);setAvOnly(false)}}>{item}</button>)}</div></div><div className="atlas-key"><span><i/> Gold highlight = AV portfolio company</span><span>If we missed something, <a href="mailto:avaneesh@av.vc">contact us here</a></span></div>{groups.map(group=><section className={`sector-group ${subsectorClass[group.name]}`} key={group.name}><header><h2>{group.name}</h2><span>{group.companies.length}</span></header><div className="wordmark-grid">{group.companies.map(company=><button id={`company-${slug(company.name)}`} className={`wordmark-item ${company.av?"av-company":""} ${pinned?.name===company.name?"pinned":""}`} key={company.name} onMouseEnter={()=>setHovered(company)} onMouseLeave={()=>setHovered(null)} onFocus={()=>setHovered(company)} onBlur={()=>setHovered(null)} onClick={()=>setPinned(company)}><Wordmark company={company}/></button>)}</div></section>)}{selected?<Detail company={selected} onClose={()=>{setPinned(null);setHovered(null)}}/>:null}</section>
}
