type Kind = "seed" | "early" | "growth";

const methods: Record<Kind,{title:string;items:Array<[string,string]>}> = {
  seed:{title:"How we selected the Seed Top 100",items:[["Scientific novelty","A genuinely new technical or biological approach."],["Horizontal potential","A path to serving many programs, labs, or drug developers."],["Founding team","Researchers and builders with clear domain depth."],["Early validation","Credible experiments, users, partners, or technical proof."],["Market timing","A real bottleneck that biology is now ready to address."],["Investor quality","Relevant deep-tech, biotech, and specialist backing."]]},
  early:{title:"How we selected the Series A/B Top 50",items:[["Platform credibility","Evidence the platform can work across repeated programs."],["External validation","Named pharmaceutical users, partnerships, or sophisticated customers."],["Technical differentiation","A defensible engine, not a familiar asset with an AI label."],["Program quality","Clear biological outputs, milestones, and multiple credible applications."],["Commercial pull","Partners investing time, data, capital, or development resources."],["Investor quality","Relevant deep-tech, biotech, and specialist backing."]]},
  growth:{title:"How we selected the Series C+ Top 25",items:[["Compounding advantage","Data, scale, or workflow adoption that improves the platform over time."],["Clinical evidence","Human, regulatory, or translational proof where appropriate."],["Platform breadth","Value across programs, customers, modalities, or development stages."],["Commercial durability","Repeat customers, strategic partnerships, and credible market pull."],["Execution quality","Evidence the company can scale science, operations, and delivery."],["Investor quality","Relevant deep-tech, biotech, and specialist backing."]]},
};

export function ResearchFooter({kind}:{kind:Kind}){const method=methods[kind];return <><section className="methodology"><p>METHODOLOGY</p><h2>{method.title}</h2><div className="method-grid">{method.items.map(([name,copy])=><article key={name}><h3>{name}</h3><p>{copy}</p></article>)}</div><small>Produced using public records and independent research conducted by summer intern <a href="https://www.linkedin.com/in/avaneesh-tisgaonkar-8210b0260" target="_blank" rel="noreferrer">Avaneesh Tisgaonkar</a>.</small></section><footer className="research-footer"><div><b>Alumni Ventures · Deep Tech Market Map</b><span>Produced using public records and independent research.</span></div><nav><a href="https://www.av.vc/ffdtsyndicate" target="_blank" rel="noreferrer">AV Deep Tech Syndicate →</a><a href="https://forms.gle/GwTqHCGjLdgZ6PGt6" target="_blank" rel="noreferrer">Founders: get in touch →</a><a href="https://forms.gle/TqTLjXFjEdAy6bEk7" target="_blank" rel="noreferrer">Want Deal Flow? →</a></nav></footer></>}
