export type Stage = "Seed" | "Series A/B" | "Series C+";

export type Company = {
  rank: number;
  name: string;
  stage: Stage;
  subsector: string;
  type: string;
  founded?: string;
};

const rows = (stage: Stage, data: Array<[string, string, string, string?]>): Company[] =>
  data.map(([name, subsector, type, founded], index) => ({ rank: index + 1, name, stage, subsector, type, founded }));

export const seedCompanies = rows("Seed", [
  ["Proxima", "AI Discovery & Bio Foundation Models", "Bioprocess Hardware"],
  ["Merge Labs", "Neurotech & BCI", "Non-Invasive BCI & Neural Interfaces"],
  ["Phylo", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology"],
  ["Edison Scientific", "Lab Automation, Agentic Science & Data Infra", "AI Scientists & R&D Agents"],
  ["Valthos", "Cell/Tissue, Ag-Vet & Biosecurity", "Biosecurity Intelligence"],
  ["Radical Numerics", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology"],
  ["Ingenix.ai", "AI Discovery & Bio Foundation Models", "Multi-Omics & Target Discovery"],
  ["Archon Bio", "AI Discovery & Bio Foundation Models", "Protein, RNA & Biologic Design"],
  ["Clair Health", "Diagnostics, Biosensors & Sample Infra", "Continuous Biosensors"],
  ["Syndex Bio", "Genomics, Omics, Proteomics & Imaging", "Methylation, Epigenomics & Epiproteomics"],
  ["Altara", "Lab Automation, Agentic Science & Data Infra", "AI Scientists & R&D Agents"],
  ["Portal Biotechnologies", "Delivery Systems", "Intracellular Delivery & Transfection"],
  ["Network Bio", "Genomics, Omics, Proteomics & Imaging", "Biomedical Data & Biobanking"],
  ["Talus Bio", "AI Discovery & Bio Foundation Models", "Multi-Omics & Target Discovery"],
  ["Convoke", "Lab Automation, Agentic Science & Data Infra", "Scientific Data & Workflow OS"],
  ["Trilobio", "Lab Automation, Agentic Science & Data Infra", "Lab Robotics & Automation"],
  ["ParcelBio", "Delivery Systems", "RNA & Lipid-Nanoparticle Delivery"],
  ["Achira", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology"],
  ["Boltz", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology"],
  ["Modulo Bio", "AI Discovery & Bio Foundation Models", "Multi-Omics & Target Discovery"],
  ["Feanix Biotechnologies", "Synthesis, Biomanufacturing & Bioprocess", "AgGenomics & Breeding"],
  ["EnPlusOne Biosciences", "Synthesis, Biomanufacturing & Bioprocess", "Synthetic Biology & Genetic-Code Engineering"],
  ["Cyclana Bio", "AI Discovery & Bio Foundation Models", "Multi-Omics & Target Discovery"],
  ["Biosphere", "Synthesis, Biomanufacturing & Bioprocess", "Bioreactors & Process Hardware"],
  ["Red Queen Bio", "Cell/Tissue, Ag-Vet & Biosecurity", "Biosecurity Intelligence"],
  ["Salt AI", "Lab Automation, Agentic Science & Data Infra", "Scientific Data & Workflow OS"],
  ["10x Science", "AI Discovery & Bio Foundation Models", "Multi-Omics & Target Discovery"],
  ["Terragia", "Synthesis, Biomanufacturing & Bioprocess", "Sustainable Fuels & Biomaterials"],
  ["Liberate Bio", "Delivery Systems", "RNA & Lipid-Nanoparticle Delivery"],
  ["Seamless Therapeutics", "Genomics, Omics, Proteomics & Imaging", "Genome-Editing Design Platforms"],
  ["Katalyze AI", "Synthesis, Biomanufacturing & Bioprocess", "Bioprocess AI & Digital Twins"],
  ["Perceptic", "Lab Automation, Agentic Science & Data Infra", "Scientific Data & Workflow OS"],
  ["Valinor", "AI Discovery & Bio Foundation Models", "Predictive Safety & Translational Models"],
  ["Bluenote", "AI Discovery & Bio Foundation Models", "Regulatory & Clinical Data AI"],
  ["Wavelet Medical", "Neurotech & BCI", "Neural Sensing & Diagnostics"],
  ["Amplifyer Bio", "Diagnostics, Biosensors & Sample Infra", "Liquid Biopsy & Molecular Diagnostics"],
  ["Granza Bio", "Delivery Systems", "Biologic, Exosome & Nanoparticle Delivery"],
  ["Mana.bio", "Delivery Systems", "RNA & Lipid-Nanoparticle Delivery"],
  ["Stately Bio", "Lab Automation, Agentic Science & Data Infra", "Analytical Instruments & Imaging"],
  ["The Biological Computing", "Cell/Tissue, Ag-Vet & Biosecurity", "Living Biological Computing"],
  ["Andson Biotech", "Lab Automation, Agentic Science & Data Infra", "Analytical Instruments & Imaging"],
  ["Zeon Systems", "Lab Automation, Agentic Science & Data Infra", "Lab Robotics & Automation"],
  ["Onepot", "Lab Automation, Agentic Science & Data Infra", "Lab Robotics & Automation"],
  ["Yoneda Labs", "Lab Automation, Agentic Science & Data Infra", "Chemistry & Reaction Informatics"],
  ["Hepta", "Diagnostics, Biosensors & Sample Infra", "Liquid Biopsy & Molecular Diagnostics"],
  ["Subsense", "Neurotech & BCI", "Non-Invasive BCI & Neural Interfaces"],
  ["Theorema AI", "Lab Automation, Agentic Science & Data Infra", "AI Scientists & R&D Agents"],
  ["Rare Air Health", "Delivery Systems", "Route-Specific Delivery"],
  ["Helical", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology"],
  ["Therna Biosciences", "AI Discovery & Bio Foundation Models", "Protein, RNA & Biologic Design"],
  ["Neurosoft Bioelectronics", "Neurotech & BCI", "Implantable & Soft Neural Interfaces"],
  ["Exthymic", "Cell/Tissue, Ag-Vet & Biosecurity", "Cell-Therapy Manufacturing"],
  ["Avenue Biosciences", "AI Discovery & Bio Foundation Models", "Protein, RNA & Biologic Design"],
  ["BlankBio", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology"],
  ["Piramidal", "Neurotech & BCI", "Neural Sensing & Diagnostics"],
  ["NeuroBionics", "Neurotech & BCI", "Implantable & Soft Neural Interfaces"],
  ["Avista Therapeutics", "Delivery Systems", "Viral-Vector Engineering & Manufacturing"],
  ["Synthesize Bio", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology"],
  ["Channel Robotics", "Diagnostics, Biosensors & Sample Infra", "Surgical Robotics & Guidance"],
  ["Strand AI", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology"],
  ["Cassidy Bio", "Genomics, Omics, Proteomics & Imaging", "Genome-Editing Design Platforms"],
  ["Trianect", "Neurotech & BCI", "Neural Sensing & Diagnostics"],
  ["NeuroHarmonics", "Neurotech & BCI", "Non-Invasive Neuromodulation"],
  ["Potato", "Lab Automation, Agentic Science & Data Infra", "AI Scientists & R&D Agents"],
  ["Caladan Bio", "Synthesis, Biomanufacturing & Bioprocess", "Bioreactors & Process Hardware"],
  ["Nanocarry", "Delivery Systems", "Biologic, Exosome & Nanoparticle Delivery"],
  ["Fuse Vectors", "Delivery Systems", "Viral-Vector Engineering & Manufacturing"],
  ["Neucore Bio", "Delivery Systems", "Biologic, Exosome & Nanoparticle Delivery"],
  ["Level Zero Health", "Diagnostics, Biosensors & Sample Infra", "Continuous Biosensors"],
  ["Neurode", "Neurotech & BCI", "Non-Invasive Neuromodulation"],
  ["NeuroDiscovery AI", "Neurotech & BCI", "Neural Sensing & Diagnostics"],
  ["Fermeate", "Synthesis, Biomanufacturing & Bioprocess", "Bioreactors & Process Hardware"],
  ["GT Bio", "Delivery Systems", "Delivery Mapping & Enablement"],
  ["DaltonTx", "AI Discovery & Bio Foundation Models", "Predictive Safety & Translational Models"],
  ["Current Surgical", "Diagnostics, Biosensors & Sample Infra", "Surgical Robotics & Guidance"],
  ["Foray Bioscience", "Synthesis, Biomanufacturing & Bioprocess", "Plant-Cell Biomanufacturing"],
  ["Rowan", "Lab Automation, Agentic Science & Data Infra", "Scientific Data & Workflow OS"],
  ["Revalia Bio", "Cell/Tissue, Ag-Vet & Biosecurity", "Organ & Tissue Research Platforms"],
  ["Breaking", "Synthesis, Biomanufacturing & Bioprocess", "Sustainable Fuels & Biomaterials"],
  ["ExpressionEdits", "Synthesis, Biomanufacturing & Bioprocess", "Synthetic Biology & Genetic-Code Engineering"],
  ["Algocell", "Synthesis, Biomanufacturing & Bioprocess", "Bioprocess AI & Digital Twins"],
  ["VALID Inc", "AI Discovery & Bio Foundation Models", "Protein, RNA & Biologic Design"],
  ["Biolevate", "Lab Automation, Agentic Science & Data Infra", "Regulatory, Quality & Medical-Writing AI"],
  ["Identifai Genetics", "Genomics, Omics, Proteomics & Imaging", "Genomic Diagnostics"],
  ["AminoChain", "Diagnostics, Biosensors & Sample Infra", "Biospecimen & Biobanking Infrastructure"],
  ["Syenex", "Delivery Systems", "Delivery Mapping & Enablement"],
  ["Kind Biotechnology", "Cell/Tissue, Ag-Vet & Biosecurity", "Organ & Tissue Research Platforms"],
  ["Reticular", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology"],
  ["Anthrogen", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology"],
  ["Orchestra", "Lab Automation, Agentic Science & Data Infra", "Scientific Data & Workflow OS"],
  ["Mito Robotics", "Lab Automation, Agentic Science & Data Infra", "Lab Robotics & Automation"],
  ["Couragene", "Delivery Systems", "Route-Specific Delivery"],
  ["Alchemi", "Lab Automation, Agentic Science & Data Infra", "Regulatory, Quality & Medical-Writing AI"],
  ["Promise Bio", "Genomics, Omics, Proteomics & Imaging", "Methylation, Epigenomics & Epiproteomics"],
  ["Ligo Biosciences", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology"],
  ["SENSEERA", "Diagnostics, Biosensors & Sample Infra", "Liquid Biopsy & Molecular Diagnostics"],
  ["Asterix Foods", "Synthesis, Biomanufacturing & Bioprocess", "Bioreactors & Process Hardware"],
  ["Rematiq", "Lab Automation, Agentic Science & Data Infra", "Regulatory, Quality & Medical-Writing AI"],
  ["CubaseBio", "Genomics, Omics, Proteomics & Imaging", "Multi-Omics & Target Discovery"],
  ["Atometra", "Lab Automation, Agentic Science & Data Infra", "Chemistry & Reaction Informatics"],
]);

export const earlyCompanies = rows("Series A/B", [
  ["Isomorphic Labs", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology", "2021"],
  ["Vivodyne", "Cell/Tissue, Ag-Vet & Biosecurity", "Predictive Safety & Translational Models", "2020"],
  ["Atrandi Biosciences", "Genomics, Omics, Proteomics & Imaging", "Multi-Omics & Target Discovery", "2016"],
  ["Latent Labs", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology", "2024"],
  ["Infinity Bio", "Genomics, Omics, Proteomics & Imaging", "Multi-Omics & Target Discovery", "2023"],
  ["Inductive Bio", "AI Discovery & Bio Foundation Models", "Predictive Safety & Translational Models", "2021"],
  ["QbDVision", "Lab Automation, Agentic Science & Data Infra", "Scientific Data & Workflow OS", "2015"],
  ["Pumpkinseed", "Genomics, Omics, Proteomics & Imaging", "Multi-Omics & Target Discovery", "2021"],
  ["Judo Bio", "Delivery Systems", "RNA & Lipid-Nanoparticle Delivery", "2021"],
  ["Countable Labs", "Diagnostics, Biosensors & Sample Infra", "Liquid Biopsy & Molecular Diagnostics", "2019"],
  ["Tacit Therapeutics", "Delivery Systems", "RNA & Lipid-Nanoparticle Delivery", "2020"],
  ["Latus", "Delivery Systems", "Viral-Vector Engineering & Manufacturing", "2020"],
  ["Neomorph", "AI Discovery & Bio Foundation Models", "Protein/RNA/Biologic Design", "2020"],
  ["UntilLabs", "Cell/Tissue, Ag-Vet & Biosecurity", "Organ & Tissue Research Platforms", "2024"],
  ["Diagonal Therapeutics", "AI Discovery & Bio Foundation Models", "Protein/RNA/Biologic Design", "2022"],
  ["Create Medicines", "Delivery Systems", "RNA & Lipid-Nanoparticle Delivery", "2019"],
  ["Hoofprint Biome", "Cell/Tissue, Ag-Vet & Biosecurity", "Ag-Vet & Biosecurity", "2022"],
  ["Santa Ana Bio", "Genomics, Omics, Proteomics & Imaging", "Multi-Omics & Target Discovery", "2020"],
  ["Arda Therapeutics", "AI Discovery & Bio Foundation Models", "Multi-Omics & Target Discovery", "2021"],
  ["Light Horse Therapeutics", "Genomics, Omics, Proteomics & Imaging", "Multi-Omics & Target Discovery", "2022"],
  ["Curve Therapeutics", "AI Discovery & Bio Foundation Models", "Protein/RNA/Biologic Design", "2019"],
  ["AIRNA", "Delivery Systems", "Genome-Editing Design Platforms", "2021"],
  ["TRIANA Biomedicines", "AI Discovery & Bio Foundation Models", "Protein/RNA/Biologic Design", "2019"],
  ["Tasca Therapeutics", "Genomics, Omics, Proteomics & Imaging", "Multi-Omics & Target Discovery", "2024"],
  ["EpiBiologics", "AI Discovery & Bio Foundation Models", "Protein/RNA/Biologic Design", "2022"],
  ["Third Arc Bio", "AI Discovery & Bio Foundation Models", "Protein/RNA/Biologic Design", "2021"],
  ["Maxion Therapeutics", "AI Discovery & Bio Foundation Models", "Protein/RNA/Biologic Design", "2020"],
  ["Auron Therapeutics", "AI Discovery & Bio Foundation Models", "Multi-Omics & Target Discovery", "2018"],
  ["Think Bioscience", "AI Discovery & Bio Foundation Models", "Chemistry & Reaction Informatics", "2021"],
  ["Ollin", "Strategic Therapeutics / Asset-Building", "Asset-Building Therapeutic Engine", "2023"],
  ["Antares Therapeutics", "AI Discovery & Bio Foundation Models", "Protein/RNA/Biologic Design", "2025"],
  ["ProLynx", "Delivery Systems", "Biologic/Exosome/Nanoparticle Delivery", "2010"],
  ["Vilya", "AI Discovery & Bio Foundation Models", "Chemistry & Reaction Informatics", "2022"],
  ["Aavantgarde", "Delivery Systems", "Viral-Vector Engineering & Manufacturing", "2021"],
  ["HAYA Therapeutics", "Delivery Systems", "Genome-Editing Design Platforms", "2019"],
  ["Congruence Therapeutics", "AI Discovery & Bio Foundation Models", "Protein/RNA/Biologic Design", "2021"],
  ["Enara Bio", "Genomics, Omics, Proteomics & Imaging", "Multi-Omics & Target Discovery", "2016"],
  ["Vico Therapeutics", "Delivery Systems", "RNA & Lipid-Nanoparticle Delivery", "2019"],
  ["Nuclidim", "Synthesis, Biomanufacturing & Bioprocess", "Radiopharmaceutical Manufacturing", "2020"],
  ["Trace Neuroscience", "Delivery Systems", "RNA & Lipid-Nanoparticle Delivery", "2024"],
  ["Link Cell Therapies", "Cell/Tissue, Ag-Vet & Biosecurity", "Cell-Therapy Manufacturing", "2022"],
  ["Nuvig Therapeutics", "Delivery Systems", "Protein/RNA/Biologic Design", "2021"],
  ["Oblenio Bio", "AI Discovery & Bio Foundation Models", "Protein/RNA/Biologic Design", "2020"],
  ["Purespring Therapeutics", "Delivery Systems", "Viral-Vector Engineering & Manufacturing", "2020"],
  ["CHARM Therapeutics", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology", "2021"],
  ["Engrail Therapeutics", "Neurotech & BCI", "Neural Sensing & Diagnostics", "2019"],
  ["Merida Biosciences", "AI Discovery & Bio Foundation Models", "Protein/RNA/Biologic Design", "2022"],
  ["NILO Therapeutics", "Neurotech & BCI", "Neural Sensing & Diagnostics", "2024"],
  ["Pinnacle Medicines", "AI Discovery & Bio Foundation Models", "Protein/RNA/Biologic Design", "2024"],
  ["Normunity", "AI Discovery & Bio Foundation Models", "Target Discovery & Biologic Design", "2020"],
]);

export const growthCompanies = rows("Series C+", [
  ["Arima Genomics", "Diagnostics, Biosensors & Sample Infra", "Liquid Biopsy & Molecular Diagnostics", "2015"],
  ["AdvanCell", "Synthesis, Biomanufacturing & Bioprocess", "Radiopharmaceutical Manufacturing", "2019"],
  ["Chai Discovery", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology", "2024"],
  ["Frontier Medicines", "Genomics, Omics, Proteomics & Imaging", "Asset-Building Therapeutic Engine", "2018"],
  ["Inflammatix", "Diagnostics, Biosensors & Sample Infra", "Liquid Biopsy & Molecular Diagnostics", "2016"],
  ["Iterative Health", "Lab Automation, Agentic Science & Data Infra", "Scientific Data & Workflow OS", "2017"],
  ["Pattern BioSciences", "Diagnostics, Biosensors & Sample Infra", "Liquid Biopsy & Molecular Diagnostics", "2016"],
  ["Precision Neuroscience", "Neurotech & BCI", "Neural Sensing & Diagnostics", "2021"],
  ["NewLimit", "AI Discovery & Bio Foundation Models", "Foundation Models & Generative Biology", "2022"],
  ["Vizgen", "Genomics, Omics, Proteomics & Imaging", "Multi-Omics & Target Discovery", "2019"],
  ["Neuralink", "Neurotech & BCI", "Neural Sensing & Diagnostics", "2016"],
  ["Synchron", "Neurotech & BCI", "Neural Sensing & Diagnostics", "2016"],
  ["Supira Medical", "Delivery Systems", "Multi-Program Precision Therapeutics", "2019"],
  ["Enveda", "AI Discovery & Bio Foundation Models", "Multi-Omics & Target Discovery", "2019"],
  ["Culture Biosciences", "Synthesis, Biomanufacturing & Bioprocess", "Scientific Data & Workflow OS", "2016"],
  ["Aidoc", "Genomics, Omics, Proteomics & Imaging", "Scientific Data & Workflow OS", "2016"],
  ["Formation Bio", "AI Discovery & Bio Foundation Models", "Asset-Building Therapeutic Engine", "2016"],
  ["EGenesis", "Cell/Tissue, Ag-Vet & Biosecurity", "Organ & Tissue Research Platforms", "2014"],
  ["Orca Bio", "Cell/Tissue, Ag-Vet & Biosecurity", "Cell-Therapy Manufacturing", "2016"],
  ["Flare Therapeutics", "Genomics, Omics, Proteomics & Imaging", "Asset-Building Therapeutic Engine", "2021"],
  ["Circle Pharma", "Synthesis, Biomanufacturing & Bioprocess", "Protein/RNA/Biologic Design", "2018"],
  ["Lycia Therapeutics", "Delivery Systems", "Biologic/Exosome/Nanoparticle Delivery", "2019"],
  ["Karius", "Diagnostics, Biosensors & Sample Infra", "Liquid Biopsy & Molecular Diagnostics", "2014"],
  ["Numab Therapeutics", "Genomics, Omics, Proteomics & Imaging", "Protein/RNA/Biologic Design", "2011"],
  ["Catalym", "Genomics, Omics, Proteomics & Imaging", "Target Discovery & Biologic Design", "2016"],
]);

export const allCompanies = [...seedCompanies, ...earlyCompanies, ...growthCompanies];
